### ISSUE TITLE
optimism:form:valid event does not fire

### ISSUE THREAD

**Issue by scottbarrow** [leastbad/optimism#19]
Im unsure how `optimism:form:valid` is intended to fire when `broadcast_errors` is only called in the controller when the resource is invalid, [as per the documentation](https://optimism.leastbad.com/quick-start#controller)

```ruby
#some controller 
    if resource.valid?
      #valid op
    else
      broadcast_errors resource, resource_params
    end
```

```javascript
//some stimulus controller
document.addEventListener('optimism:form:valid', () => this.someEvent())
document.addEventListener('optimism:form:invalid', () => this.someEvent())
```

With a valid resource
  Expected `optimism:form:valid` broadcast
  Actual does not broadcast
With an invalid resource
  Expected `optimism:form:invalid` broadcast
  Actual == Expected

However, if I place `broadcast_errors` outside the `valid?` conditional and allow it to do its own `model.valid?` as per [the code](https://github.com/leastbad/optimism/blob/master/lib/optimism.rb#L41) it does fire the event

```ruby
#some controller 
    if resource.valid?
      #valid op
    else
      #noop
    end
    broadcast_errors resource, resource_params
```

With a valid resource
  Expected `optimism:form:valid` broadcast
  Actual == Expected

Does Optimism support `broadcast_errors` for both valid and invalid paths? How otherwise is form:valid expected to be emitted and consumed?

**Comment by scottbarrow** [comment]
@leastbad 

I understand this is an error path intended method, my trying to use it for something it wasn't intended to do was an attempt to get the happy path out of the gem to emit the optimism:form:valid event. Otherwise [line 47](https://github.com/leastbad/optimism/blob/master/lib/optimism.rb#L47) seems to be an unreachable path

My assumption that Optimism was doing validation is from https://github.com/leastbad/optimism/blob/master/lib/optimism.rb#L41
Since this is where `optimism:form:valid` is broadcast on line 48. This is why I suggested above to have Optimism handle validation and returning the result of which. 

If the only way for me to get a form:valid event emitted is moving the broadcast_errors call outside of the resource validation condition in the controller action as per my example below, but as I say the method name in this case does not communicate correct intent in the case of the happy path.

My suggestion seems to have been misunderstood, Im suggesting that Optimism could have a method the encompasses both happy and sad path

```ruby
#some controller 
    if resource.valid?
      #valid op
    else
      #noop
    end
    broadcast_errors resource, resource_params
```

**Comment by scottbarrow** [comment]
@leastbad sorry to bug you on this again, but we're trying to determine if Optimism is a suitable fit to replace error handling _and_ successful model updates. 
Do you have any further thoughts on my comment above and whether you would consider a PR to allow Optimism to handle happy paths?

**Comment by leastbad** [comment]
I understand, Scott. I'm thinking about it, and I'm a volunteer so please don't send me impatient sounding follow-ups.

**Comment by scottbarrow** [comment]
Apologies, that wasn't my aim, I am willing to contribute but just want to confirm if it would be valuable
