### ISSUE TITLE
Demo dead

### ISSUE THREAD

**Issue by davidlesches** [leastbad/optimism#20]
Hi - just wanted to point out that the demo doesn't seem to work. Nothing happens when filling in inputs.

**Comment by leastbad** [comment]
Hi David,

Thanks for the heads up. I just tried the app and it is working as expected.

Nothing is supposed to happen when filling in inputs. The validation occurs on submit.

I suggest reading the documentation: https://optimism.leastbad.com/

**Comment by davidlesches** [comment]
Ah apologies, I misunderstood. Thanks

**Comment by leastbad** [comment]
No worries, my friend. Let me know if you have any further questions. Discord is also an excellent way to reach me for casual questions.
